name: 'Code Linting'

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: 14.x
      - uses: actions/cache@master
        id: cacheNodeModules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - name: yarn install
        if: steps.cacheNodeModules.outputs.cache-hit != 'true'
        run: yarn install
      - run: yarn lint
        env:
          CI: true
